# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "ntec.io - tech & programming"
languageCode = "de-DE"
baseURL = "https://ntec.io/"
copyright = "Â© {year}"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/ntec_io"
  github = "https://github.com/ntec-io"
  # email = "mailto:ntecvideos@gmail.com"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/ntec-io"
  # linkedin = "<link to your profile>"
  youtube = "https://www.youtube.com/channel/UCWlzQ62V0vhtH1XkgN4hS2A"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["YouTube", "GitHub", "Instagram", "Twitter"]

  # Metadata for Twitter cards, defaults to params.twitter
  twitterSite = "@ntec_io"
  twitterAuthor = "@nicolas_goldack"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  
